### ISSUE TITLE
[Feature] Make optional if the sudo cookie should be reset on login

### ISSUE THREAD

**Issue by gabn88** [mattrobenolt/django-sudo#16]
Maybe it would be an idea to tell people that they have to remove the sudo cookie themselves on logout. Otherwise it will come back on login.

**Comment by gabn88** [comment]
Just to clarify: It does remove the sudo cookie, but on relogin it will be set again. In my case this is uninteded behaviour, but I had to find out the hard way. It would be nice to have this in the docs.

Thank you for this great module for the rest! :+1:

**Comment by gabn88** [comment]
Let's make a feature of this!

By default, a sudo cookie will be reset on login. A.k. when the general setting is that a cookie should be valid for 3 hours, and a users logs in (even on another device!) after 2:59 minutes, the user will again have sudo permissions. 
Of course logging in requires the password again, but for my application it is very important that the user can't do/show something stupid, which he could when he has sudo permissions.

For my application this is unwanted/unsafe, so it would be really cool to make a this a setting.

**Comment by moggers87** [comment]
You can already do this by disconnecting the grant signal handler:

```
user_logged_in.disconnect(sudo.signals.grant)
```

**Comment by gabn88** [comment]
Where should I place this code? It is not very clean, is it?

**Comment by moggers87** [comment]
In your [AppConfig](https://docs.djangoproject.com/en/1.8/ref/applications/) or your `models.py` if you're using an older version of Django.

**Comment by gabn88** [comment]
Thanks, it is working in models.py! 👍
