### ISSUE TITLE
Redirect to requested page on successful sudo login

### ISSUE THREAD

**Issue by umgelurgel** [mattrobenolt/django-sudo#9]
I'd like to use `django-sudo` in a project I'm working on where a user can access `update-email` and `update-password` views. I'd like to wrap them both with `sudo_required()`, but I find it counterintuitive that the user gets redirected to the same page upon confirming their password. I realise the url parameter `SUDO_REDIRECT_FIELD_NAME` is missing from the post - but it should be possible to achieve that behaviour using session parameters, right? Or am I missing something?

Thanks for your work on this module!

**Comment by mattrobenolt** [comment]
Fixed by #10.
